TI-4605: Update snakex to Django 4.2
diurnate/wagtail-personalisation pull request #7
Opened 2024-04-16 14:46 UTC by easherma-truth

https://truthinnovations.atlassian.net/browse/TI-4605

2024-05-09 13:59 UTC, truthbyron commented
The single comment should be reworded to fix the ticket ID.

2024-05-20 21:27 UTC, truthdoug submitted a review, later dismissed

2024-05-20 21:46 UTC, truthdoug requested changes, later dismissed
Please fix the ticket id in the commit

2024-06-17 19:53 UTC, truthbyron approved these changes

2024-06-17 19:54 UTC, merged